# <center>Numpy</center>

## Numpy概述

### 1.1 Numpy简介
NumPy是使用Python进行科学计算的基础包。它包含其他内容：

- 一个强大的N维数组对象

- 复杂的（广播）功能

- C 实现，执行效率高

- 有用的线性代数，傅里叶变换和随机数功能

### 1.2 Numpy的安装
*方法一：*    
 标准的 Python 发行版不会与 NumPy 模块捆绑在一起。一个轻量级的替代方法是使用流行的Python 包安装程序 pip 来安装 NumPy。    
 在 CMD 或命令行中执行: pip install numpy    
 
 *方法二：* （推荐）      
 但是实际在 Windows 系统中的安装，多数时候会出现各类需要编译或缺乏相关依赖的问题，由于在 Python 的编程基础部分已经提过，建议大家使用 Anaconda 的 Python 发行版，这个发行版已经提前为我们安装了各类的科学计算需要的第三方包,其中就包含了numpy,可以直接使用。    

## Numpy-Ndarray对象 

Numpy 的核心是 ndarray 对象，这个对象封装了同质数据类型的n维数组。（数组，即为有序的元素序列）     
ndarray 是 n-dimension-array 的简写。

Numpy 约定俗成的导入方式如下：

In [1]:
import numpy as np

In [2]:
#全部行都能输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### 2.1 创建Ndarray

#### 方法一 : np.array函数

创建一个 ndarray 只需调用 NumPy 的 array 函数即可：

numpy.array()

In [12]:
#创建一维数组
arr1 = np.array([1, 3.14, -5, 2, 6.2, 0])  #要生成的array中的元素必须打包到一个序列作为一个参数传入函数中
arr1

array([ 1.  ,  3.14, -5.  ,  2.  ,  6.2 ,  0.  ])

In [82]:
#创建二维数组
arr2 = np.array([[5,6,7,8,9],[4,3,2,1,0]])
arr2

array([[5, 6, 7, 8, 9],
       [4, 3, 2, 1, 0]])

In [5]:
#通过ndmin参数控制生成数组的维度
arr3 = np.array([1,2,3,4,5], ndmin=2)
arr3

array([[1, 2, 3, 4, 5]])

In [80]:
#创建三维数组
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
#通过ndmin参数控制生成数组的维度
arr5 = np.array([0,1,2,3],ndmin=3)
arr5

array([[[0, 1, 2, 3]]])

#### 方法二 : 随机数函数生成array

用随机整数函数生成array时,设置参数size来控制array的维度

随机数函数不设置随机数种子的时候,每次生成的数组包含的元素都是不一样的

In [8]:
#创建一维数组
arr6 = np.random.randint(10,size=(4,))  #必须设置size参数,否则只生成一个随机数
arr6

array([6, 8, 4, 8])

In [9]:
#创建二维数组
arr7 = np.random.randint(20,size=(4,5))
arr7

array([[15,  4, 16,  0, 11],
       [14, 11,  8,  2,  0],
       [ 8,  7, 14,  2, 14],
       [ 7,  4,  3, 14, 15]])

In [87]:
#创建三维数组
arr8 = np.random.randint(60,size=(3,4,5))
arr8

array([[[46,  2, 31, 20, 42],
        [ 4, 55, 30, 31, 15],
        [30, 29,  9, 11,  9],
        [21, 32, 44, 51,  7]],

       [[17, 35, 49, 15, 49],
        [59, 18, 40, 41, 22],
        [57, 55, 47, 34,  7],
        [21, 19, 42, 39, 45]],

       [[23, 22, 34, 45,  1],
        [59, 59, 32, 30, 22],
        [45, 54, 28, 20, 13],
        [45, 24, 47, 43, 16]]])

In [11]:
#元素取值从0到1服从均匀分布
np.random.rand(2,3,4)

array([[[0.52743029, 0.97996594, 0.05121362, 0.14728815],
        [0.14649511, 0.05100129, 0.55513112, 0.57293498],
        [0.41445543, 0.5104456 , 0.87877002, 0.37898923]],

       [[0.00420524, 0.86279789, 0.44534523, 0.22361147],
        [0.67049263, 0.8258309 , 0.65235685, 0.87998838],
        [0.19722391, 0.85747402, 0.61654684, 0.56418669]]])

In [10]:
np.random.uniform(size = (2,3)) #默认生成从0~1的均匀分布,可以通过参数设置随机数生成范围

array([[0.52992644, 0.97698767, 0.32889695],
       [0.57476293, 0.61213951, 0.81297723]])

In [11]:
np.random.uniform(1,10,size = (2,3)) #默认生成从0~1的均匀分布,可以通过参数设置随机数生成范围

array([[8.15406388, 3.10594869, 8.05073268],
       [2.14242958, 9.71912885, 5.62135875]])

In [13]:
#元素取值从[0,1)随机浮点数并服从连续均匀分布,参数为元组形式
np.random.random((2,3))

array([[0.98427243, 0.9051764 , 0.21385441],
       [0.29707207, 0.5683221 , 0.57083584]])

In [12]:
#元素取值服从标准正态分布
np.random.randn(2,3)

array([[ 0.24618198,  0.34854709,  0.89156417],
       [ 0.02844626, -0.02647052,  1.20060679]])

#### 方法三 : 用arange函数创建array
可以用reshape函数来控制生成array的维度

In [14]:
#创建一维数组
arr9 = np.arange(1,10)  #还可以设置步长
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#创建二维数组
arr10 = np.arange(12).reshape((3,4))
arr10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#创建三维数组
arr11 = np.arange(24).reshape((2,3,4))
arr11

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### 方法四 : 创建特殊数组函数:
- np.zeros np.zreos_like 全0数组
- np.ones np.ones_like  全1数组
- np.full  np.full_like 按照某一数组的形状生成数组
- np.linspace 线性序列数组(元素之间等差)
- np.eye  单位矩阵数组
- np.empty 创建初始化数组
- np.diag 对角矩阵数组

全0数组

In [17]:
#一维全0数组
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
#指定形状的全0数组
np.zeros((3,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#创建和已存在数组形状相同的全0数组
np.zeros_like(arr10)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

全1数组

In [20]:
#一维全1数组
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
#指定形状的全1数组
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#创建和已存在数组形状相同的全1数组
np.ones_like(arr10)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

全n数组

In [23]:
#创建一维全n数组
np.full((3,),3)

array([3, 3, 3])

In [24]:
#创建指定形状的全n数组
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [25]:
#创建和已存在数组形状相同的全n数组
np.full_like(arr10,3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

线性序列数组,所有元素组成一个等差数列

In [26]:
#创建线性序列,可以倒序,起始值大于终止值
np.linspace(10,5,5) 

array([10.  ,  8.75,  7.5 ,  6.25,  5.  ])

In [27]:
#linspace创建的array需要通过reshape函数改变形状维度,不能和retstep参数一起使用
np.linspace(0,50,21).reshape(3,7)

array([[ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ],
       [17.5, 20. , 22.5, 25. , 27.5, 30. , 32.5],
       [35. , 37.5, 40. , 42.5, 45. , 47.5, 50. ]])

In [28]:
#显示步长
np.linspace(0,50,5,retstep=True)  

(array([ 0. , 12.5, 25. , 37.5, 50. ]), 12.5)

In [29]:
#默认包含终止值,通过endpoint参数控制是否包含终止值
np.linspace(0,50,5,retstep=True, endpoint=False)

(array([ 0., 10., 20., 30., 40.]), 10.0)

单位矩阵

In [30]:
#创建单位矩阵 默认数值类型为浮点型
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#参数k控制对角线偏移
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [32]:
#可以直接输入需要的矩阵形状
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

创建对角矩阵数组

In [36]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [37]:
np.diag([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

创建初始化数组

In [32]:
np.empty(6,order='C')

array([8.15406388, 3.10594869, 8.05073268, 2.14242958, 9.71912885,
       5.62135875])

In [33]:
np.empty(6,order='F')

array([8.15406388, 3.10594869, 8.05073268, 2.14242958, 9.71912885,
       5.62135875])

In [37]:
arr12 = np.empty((2,3), order='C')
arr12

array([[8.15406388, 9.71912885, 2.14242958],
       [8.05073268, 3.10594869, 5.62135875]])

In [35]:
arr12.fill(3)
arr12

array([[3., 3., 3.],
       [3., 3., 3.]])

总结一下,创建数组的要点,一是指定数组内的元素都是什么,而是指定数组的形状是什么样子的,从这两方面考虑如何创建一个符合自己需求的数组

**练习**

- 1 通过np.array()创建数组,通过参数控制数组维度
- 2 通过随机数函数生成数组,分别生成服从均匀分布\正态分布\元素类型为整数型的数组
- 3 通过数组元素为连续整数型的数组,通过reshape方法控制数组的维度
- 4 生成全零数组,全一数组,全n数组,单位矩阵,对角矩阵,线性序列数组,空数组,维度随意

### numpy的矢量化功能

#### ndarray和python原生序列的区别

NumPy 数组在创建时有固定的大小，不同于Python列表（可以动态改变)。

NumPy 数组中的元素都需要具有相同的数据类型，计算速度更快。

数组的元素如果也是数组（可以是 Python 的原生 array，也可以是 ndarray）的情况下，则构成了多维数组。

#### numpy的矢量化(向量化)功能

- 数组表达式替换显式循环的做法通常称为向量化

In [38]:
# 将一个二维数组 a 的每个元素与长度相同的另外一个数组 b 中相应位置的元素相乘,使用 Python 原生的数组实现如下：

In [75]:
a = [1,2,3]
b = [4,5,6]
a
b

[1, 2, 3]

[4, 5, 6]

In [76]:
c = []
for i in range(3):
    c.append(a[i]+b[i])

In [77]:
c

[5, 7, 9]

In [13]:
# c=a*b #这样写可以么？

使用numpy实现a与b的对应元素相乘

In [42]:
arr13 = np.array(a)
arr14 = np.array(b)
arr13
arr14

array([[1, 2, 3],
       [5, 7, 8],
       [4, 5, 6]])

array([[6, 2, 1],
       [2, 3, 1],
       [4, 5, 6]])

In [43]:
#实现对应元素相乘
arr13*arr14

array([[ 6,  4,  3],
       [10, 21,  8],
       [16, 25, 36]])

In [44]:
#实现对应元素相加
arr13+arr14

array([[ 7,  4,  4],
       [ 7, 10,  9],
       [ 8, 10, 12]])

In [45]:
#实现对应元素相除
arr13/arr14

array([[0.16666667, 1.        , 3.        ],
       [2.5       , 2.33333333, 8.        ],
       [1.        , 1.        , 1.        ]])

In [46]:
#实现对应元素相减
arr13-arr14

array([[-5,  0,  2],
       [ 3,  4,  7],
       [ 0,  0,  0]])

In [47]:
arr13

array([[1, 2, 3],
       [5, 7, 8],
       [4, 5, 6]])

In [48]:
#所有元素对一个数值的加减乘除
arr13+1

array([[2, 3, 4],
       [6, 8, 9],
       [5, 6, 7]])

In [49]:
arr13*2

array([[ 2,  4,  6],
       [10, 14, 16],
       [ 8, 10, 12]])

矢量化代码有很多优点，其中包括：

- 矢量化代码更简洁易读
- 更少的代码行通常意味着更少的错误
- 执行效率高，运行速度快

### ndarray的属性
- ndarray.shape 返回一个包含数组维度的元组
- ndarray.dtype 返回数组元素的类型
- ndarray.ndim 返回数组的维数
- ndarray.size 返回数组中包含元素的个数
- ndarray.itemsize 返回数组中每个元素的字节单位长度(只做了解)

In [5]:
#为了确保大家都能生成一样的数组, 我们先设置随机数种子
import numpy as np
np.random.seed(123)
arr15 = np.random.randint(10, size=6) # 一维数组
np.random.seed(123)
arr16 = np.random.randint(10, size=(3, 4)) # 二维数组
np.random.seed(123)
arr17 = np.random.randint(10, size=(3, 4, 5)) # 三维数组
    
print(arr15)
print(arr16)
print(arr17)

[2 2 6 1 3 9]
[[2 2 6 1]
 [3 9 6 1]
 [0 1 9 0]]
[[[2 2 6 1 3]
  [9 6 1 0 1]
  [9 0 0 9 3]
  [4 0 0 4 1]]

 [[7 3 2 4 7]
  [2 4 8 0 7]
  [9 3 4 6 1]
  [5 6 2 1 8]]

 [[3 5 0 2 6]
  [2 4 4 6 3]
  [0 6 4 7 6]
  [7 1 5 7 9]]]


In [51]:
arr15
arr16 
arr17

array([2, 2, 6, 1, 3, 9])

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

array([[[4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8],
        [0, 7, 9, 3, 4],
        [6, 1, 5, 6, 2]],

       [[1, 8, 3, 5, 0],
        [2, 6, 2, 4, 4],
        [6, 3, 0, 6, 4],
        [7, 6, 7, 1, 5]],

       [[7, 9, 2, 4, 8],
        [1, 2, 1, 1, 3],
        [5, 9, 0, 8, 1],
        [6, 3, 3, 5, 9]]])

In [52]:
#查看数组的形状
arr15.shape
arr16.shape
arr17.shape

(6,)

(3, 4)

(3, 4, 5)

In [53]:
#查看数组中元素的类型
arr15.dtype
arr16.dtype
arr17.dtype

dtype('int32')

dtype('int32')

dtype('int32')

In [54]:
#查看维度
arr15.ndim
arr16.ndim
arr17.ndim

1

2

3

In [55]:
#查看元素个数
arr15.size
arr16.size
arr17.size

6

12

60

In [22]:
# #查看数组中每个元素的字节单位长度(int8为一个字节,元素数据类型为int32,所以字节长度是4)
# arr15.itemsize
# arr16.itemsize
# arr17.itemsize

### ndarray的各种变换操作

|数组的维度变换|数组的类型变换|数组内元素类型变换|
|--------------|--------------|------------------|
|ndarray.reshape|ndarray.tolist|ndarray.astype|
|ndarray.resize | 
|ndarray.flatten|
|ndarray.swapaxes|

#### 数组的维度变换

In [57]:
arr18 = np.random.randint(1, 100,(2, 2, 2))
arr18

array([[[99,  4],
        [12,  4]],

       [[95,  7],
        [10, 88]]])

In [58]:
#reshape返回调整后的数组形状,不改变原数组
arr18.reshape(2,4)

array([[99,  4, 12,  4],
       [95,  7, 10, 88]])

In [6]:
import numpy as np
arr18 = np.random.randint(1, 100,(2, 2, 2))
arr18.reshape(2,5)
arr18

ValueError: cannot reshape array of size 8 into shape (2,5)

In [259]:
#reshape的特殊用法一
arr18.reshape(1,-1)

array([[99,  4, 12,  4, 95,  7, 10, 88]])

In [60]:
#reshape的特殊用法二
arr18.reshape(-1,1)

array([[99],
       [ 4],
       [12],
       [ 4],
       [95],
       [ 7],
       [10],
       [88]])

In [61]:
arr18.shape

(2, 2, 2)

In [ ]:
arr19 = arr18.copy()

In [62]:
#resize返回调整后的形状,改变原数组
arr19.resize(4,2)

In [63]:
arr19.shape

(4, 2)

In [64]:
#flatten()把高维的数组展平成一维,观察与reshape(1,-1)结果的不同
arr18.flatten()

array([99,  4, 12,  4, 95,  7, 10, 88])

In [65]:
arr16

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [66]:
##swapaxes将两个维度调换,不改变原数组
arr16_1=arr16.swapaxes(0,1)
arr16_1

array([[6, 9, 3],
       [1, 0, 4],
       [0, 0, 0],
       [1, 9, 0]])

In [67]:
#二维数组的转置,也可以用.T实现
arr16.T

array([[6, 9, 3],
       [1, 0, 4],
       [0, 0, 0],
       [1, 9, 0]])

#### 数组的类型变换

In [260]:
#tolist不改变原数组,将高维数组转换为嵌套列表,一维数组转换为列表
arr16.tolist()

list

In [69]:
arr1.tolist()

[1.0, 3.14, -5.0, 2.0, 6.2, 0.0]

In [70]:
type(arr1.tolist())

list

#### 数组内元素类型的变换

In [71]:
arr16.dtype

dtype('int32')

In [72]:
#astype不改变原数组
arr16.astype(float)

array([[6., 1., 0., 1.],
       [9., 0., 0., 9.],
       [3., 4., 0., 0.]])

In [73]:
arr16.astype(str)

array([['6', '1', '0', '1'],
       ['9', '0', '0', '9'],
       ['3', '4', '0', '0']], dtype='<U11')

### 数据科学中常用的数组计算操作

|拆分|合并|拷贝|排序|缺失值处理|提取特征向量|广播|
|----|----|----|----|------------|--------|------|
|np.split|np.concatenate|浅拷贝 "="|np.sort|np.nan|np.newaxis|不同形状的数组之间的+/-操作|
|np.vsplit|np.stack|深拷贝 .copy()|np.argsort|np.isnan|-|先广播后计算|
|np.hsplit|np.vstack|-|-|np.any/all(np.isnan)|-|-|
|-|np.hstack|-|-|np.nansum|-|-|

#### ndarray拆分:
- np.split 
- np.vsplit 横向切分
- np.hsplit 纵向切分

In [26]:
arr20 = np.random.randint(10,size = (2, 6))
arr20

array([[3, 4, 3, 1, 0, 5],
       [8, 6, 8, 9, 1, 0]])

In [27]:
np.split(arr20,2)  #默认axis=0,和vsplit的作用一样

[array([[3, 4, 3, 1, 0, 5]]), array([[8, 6, 8, 9, 1, 0]])]

In [28]:
np.vsplit(arr20,2)  #把列切开,行信息不被损坏

[array([[3, 4, 3, 1, 0, 5]]), array([[8, 6, 8, 9, 1, 0]])]

In [29]:
np.split(arr20, 3,axis=1)    #可以设置axis=1,和hsplit的作用一样

[array([[3, 4],
        [8, 6]]), array([[3, 1],
        [8, 9]]), array([[0, 5],
        [1, 0]])]

In [30]:
np.hsplit(arr20, 3)   #把行切开,列信息不被损坏

[array([[3, 4],
        [8, 6]]), array([[3, 1],
        [8, 9]]), array([[0, 5],
        [1, 0]])]

In [79]:
arr21 = np.arange(8.0)
arr21

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [80]:
#第二参数可以是整数,也可以是列表,列表内的整数表示分割位置,在该位置前切割,如果指定的位置超出被分割array的范围,会多返回一个空array
np.split(arr21, [3,5,10])  

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5., 6., 7.]),
 array([], dtype=float64)]

In [81]:
np.split(arr21, [3,5])

[array([0., 1., 2.]), array([3., 4.]), array([5., 6., 7.])]

#### ndarray的合并:
- np.concatenate 拼接后维度不变  
- np.stack 拼接后增加维度 
- np.vstack 和 np.hstack  拼接后维度不变

In [78]:
arr22 = np.arange(10).reshape(2,5)
arr23 = np.arange(10,20).reshape(2,5)
arr22
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
np.concatenate((arr22,arr23))  #默认axis=0  按行拼接,拼接后列数不变

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
np.concatenate((arr22,arr23),axis=1) #axis=1 按列进行拼接,拼接后行数不变

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [85]:
np.stack([arr22,arr23])  #拼接后增加了一个维度

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [82]:
np.stack([arr22,arr23],axis=1)

array([[[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]]])

In [83]:
np.stack([arr22,arr23],axis=-1)

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14]],

       [[ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

In [86]:
np.stack([arr22,arr23]).shape

(2, 2, 5)

In [87]:
np.vstack((arr22,arr23))  #按行拼接,列数不变,前提是列数一样

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
np.hstack((arr22,arr23))  #按列拼接,行数不变,前提是行数一样

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

#### 拷贝:浅拷贝和深拷贝 
- 浅拷贝直接"="引用
- 深拷贝用.copy()方法

In [84]:
arr24 = np.arange(10)
arr24

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr25=arr24  #浅拷贝   复制过来的是'引用',复制对象和被复制对象共享一个存储空间,二者不是相互独立的
arr25

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr25[4:7]=1

NameError: name 'arr25' is not defined

In [87]:
arr25

array([0, 1, 2, 3, 1, 1, 1, 7, 8, 9])

In [88]:
arr24

array([0, 1, 2, 3, 1, 1, 1, 7, 8, 9])

In [41]:
arr26 = np.arange(10)
arr26

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr27 = arr26.copy()  #深拷贝,拷贝后的数组与原数组是完全独立的两个数组
arr27

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr27[4:7]=1

In [44]:
arr27

array([0, 1, 2, 3, 1, 1, 1, 7, 8, 9])

In [45]:
arr26

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 排序
- np.sort 返回排序结果
- np.argsort 返回排序后的索引

In [46]:
arr28 = np.array([10,17,12,11,18,14,13,16,15])
arr28

array([10, 17, 12, 11, 18, 14, 13, 16, 15])

In [47]:
np.sort(arr28)  #返回排序结果

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [100]:
np.argsort(arr28)  #返回排序的索引

array([0, 3, 2, 6, 5, 8, 7, 1, 4], dtype=int64)

In [48]:
arr29 = np.array([[21,22,23,24,25],[35,34,33,32,31],[1,2,3,99,4]])
arr29

array([[21, 22, 23, 24, 25],
       [35, 34, 33, 32, 31],
       [ 1,  2,  3, 99,  4]])

In [49]:
np.sort(arr29,axis=1)  #多维数组按指定维度进行排序,axis=1 计算前后行数不变,以行为单位,每行独立计算,逐行计算

array([[21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [ 1,  2,  3,  4, 99]])

In [50]:
np.sort(arr29,axis=0)  #axis=0 计算前后列数不变,以列为单位,每列独立计算,逐列计算

array([[ 1,  2,  3, 24,  4],
       [21, 22, 23, 32, 25],
       [35, 34, 33, 99, 31]])

In [51]:
np.sort(arr29,axis=-1) 

array([[21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [ 1,  2,  3,  4, 99]])

#### 缺失值处理
- numpy中的缺失值-np.nan
- 判断数组元素是否为缺失值-np.isnan
- 判断数组中是否至少有一个缺失值-np.any()
- 判断数组中所有元素是否全部为缺失值-np.all()
- 缺失值的处理-np.nansum()

In [52]:
# numpy中的缺失值
np.nan

nan

In [53]:
#np.nan的数据类型是浮点型,可以参加算术运算
type(np.nan)

float

In [89]:
arr30 = np.array([np.nan,1,2,np.nan,3,4,5])
arr30

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [55]:
#判断数组中是否有缺失值
np.isnan(arr30)

array([ True, False, False,  True, False, False, False])

In [64]:
# 判断数组中是否至少有一个缺失值,np.any嵌套np.isnan
np.any(np.isnan(arr30))

True

In [94]:
# 判断数组中所有元素是否全部为缺失值,np.any嵌套np.isnan
np.all(np.isnan(arr30))

False

In [97]:
#带缺失值进行计算
sum(arr30)

nan

In [111]:
#虽然计算结果依然是nan,但是计算后生成的nan和最开始的np.nan是不一样的,可以通过id来进行判断
id(sum(arr30))

2176710956928

In [112]:
id(np.nan)

2176706111264

In [113]:
#缺失值的处理方法一:取非
sum(arr30[(~np.isnan(arr30))])

15.0

In [76]:
arr30[~np.isnan(arr30)]

array([1., 2., 3., 4., 5.])

In [114]:
#缺失值的处理方法二:np.nansum
np.nansum(arr30)

15.0

#### 提取特征向量
- np.newaxis 定义一个新维度(new axis)

In [115]:
arr1 

array([ 1.  ,  3.14, -5.  ,  2.  ,  6.2 ,  0.  ])

In [116]:
#是规整化处理特征向量的一种方法
arr1[:,np.newaxis]

array([[ 1.  ],
       [ 3.14],
       [-5.  ],
       [ 2.  ],
       [ 6.2 ],
       [ 0.  ]])

In [117]:
arr1.shape

(6,)

In [118]:
arr1[:,np.newaxis].shape

(6, 1)

#### 广播
如果满足以下条件之一，那么数组被称为可广播的。
- 如果数组不具有相同的秩，则将较低等级数组的形状维度添加1，直到两个形状具有相同的大小.
- 其中一个数组的维度大小和元素个数为1，相当于对单个标量进行广播
- 在一个数组的大小为1且另一个数组的大小大于1的任何维度中，第一个数组的行为就像沿着该维度复制一样

给出广播示意图：

![_auto_0](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [77]:
#列数相同,一行加多行
a=np.arange(3)
a

array([0, 1, 2])

In [78]:
b=np.array([1])
b

array([1])

In [79]:
#第一幅图
a+b

array([1, 2, 3])

In [122]:
#第一幅图
a+1

array([1, 2, 3])

In [82]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
#第二幅图
a+c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [84]:
d=a[:,np.newaxis]
d

array([[0],
       [1],
       [2]])

In [85]:
#第三幅图
a+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [86]:
#单个标量和数组的运算
b+1

array([2])

In [128]:
#不满足广播条件的数组无法进行广播
e= np.arange(4).reshape(2,2)
e

array([[0, 1],
       [2, 3]])

In [129]:
a+e 

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [130]:
e+b  #b广播到和e相同的形状

array([[1, 2],
       [3, 4]])

### 访问ndarray中的元素--索引和切片
- 一维数组基本索引和切片 高维数组基本索引和切片 
- 高级索引和切片:花式索引切片 整数数组索引切片 布尔索引切片
- 通过索引和切片改变数组元素值

#### 基本索引和切片

- 索引 : ndarray 数组可以基于 0 - n 的下标进行索引
- 切片 : 通过内置的 slice 函数并设置 start, stop 及 step 参数，从原数组中切割出一个新数组

##### 一维数组的索引和切片

In [176]:
arr31 = np.arange(10)
arr31

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
#索引下标为3的元素值
arr31[3]

3

In [133]:
#切片 设置起始值 终止值 步长,用冒号隔开,返回的数组不包含终止值 
arr31[2:8:2]

array([2, 4, 6])

In [134]:
#不设置步长,默认步长为1
arr31[2:8]

array([2, 3, 4, 5, 6, 7])

In [135]:
#不设置终止值,默认切片到最后
arr31[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
#不设置起始值,默认从第0个元素开始
arr31[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [137]:
#起始值 终止值 都不设置,默认从头切到尾
arr31[::2]

array([0, 2, 4, 6, 8])

In [138]:
#什么都不设置,默认全切,但是注意中括号内要放入冒号表示从头切到尾,步长为默认步长
arr31[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
#可以从后往前切,注意起始值到终止值的方向和步长方向一致
arr31[8:2:-2]

array([8, 6, 4])

In [186]:
arr31

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
#切取不连续的指定元素,通过下标位置切取,把需要切取的位置下标放入列表当中
arr31[[1,2,5,9]]

array([1, 2, 5, 9])

##### 高维数组的基本索引和切片

In [87]:
arr32 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr32

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
# 索引下标为1的array
arr32[1]

array([4, 5, 6])

In [142]:
#切片从下标为1到最后的array
arr32[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [143]:
# 用逗号分隔后,逗号前表示对行的切片,逗号后表示行切片后对列进行的切片
arr32[1:,1:]

array([[5, 6],
       [8, 9]])

In [89]:
#切取单个元素,先切出元素所在的行,再在行中找到元素所在的下标
arr32[1][1]

5

In [96]:
# 切取单个元素也可以用这种方式,逗号前是元素所在行信息,逗号后是元素所在列信息
arr32[1,1]

5

##### 基本切片形成视图
通过基本切片生成的所有数组始终是原始数组的视图,与原数组共享内存，修改其中一个数组，另一个数组同时也会被修改

In [216]:
arr31

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
arr31[2:4]=66

In [218]:
arr31

array([ 0,  1, 66, 66,  4,  5,  6,  7,  8,  9])

In [219]:
arr31_c=arr31[2:6]  #前边将过的浅拷贝
arr31_c

array([66, 66,  4,  5])

In [220]:
arr31_c[0:2]=88

In [221]:
arr31_c
arr31

array([88, 88,  4,  5])

array([ 0,  1, 88, 88,  4,  5,  6,  7,  8,  9])

如果不想获得视图,而是需要得到数据的副本,用copy()函数

In [222]:
arr31_copy=arr31[2:6].copy()
arr31_copy

array([88, 88,  4,  5])

In [223]:
arr31_copy[0:2]=99
arr31_copy

array([99, 99,  4,  5])

In [224]:
arr31

array([ 0,  1, 88, 88,  4,  5,  6,  7,  8,  9])

####  高级索引:整数索引和布尔索引

##### 整数索引

In [91]:
arr33 = np.array([[1, 2], [3, 4], [5, 6]])
arr33

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
arr33[[0, 1, 2], [0, 1, 0]]  #[0,1,2]表示第0行,第1行,第2行;[0,1,0]表示第0列,第1列,第0列,和前边切取单个元素的原理一样

array([1, 4, 5])

In [175]:
row = np.array([0, 1, 2])
col = np.array([0, 1, 0])
arr33[row,col]

array([1, 4, 5])

##### 高级索引形成副本
高级索引始终返回数据的副本（与返回视图的基本切片形成对比）

In [225]:
arr31_c=arr33[[0, 1, 2], [0, 1, 0]]
arr31_c[:]=9

In [226]:
arr31_c
arr31

array([9, 9, 9])

array([ 0,  1, 88, 88,  4,  5,  6,  7,  8,  9])

##### 切片中的广播函数  np.ix_

In [227]:
arr33

array([[1, 2],
       [3, 4],
       [5, 6]])

In [193]:
arr33[[0,1],[0,1]]

array([1, 4])

In [191]:
arr33[np.ix_([0,1],[0,1])]  #所谓广播,是只原来只描述两个位置的信息,被广播描述四个位置信息

array([[1, 2],
       [3, 4]])

In [195]:
arr33[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [194]:
arr33[np.ix_([0,1,2],[0,1,0])]  #原来描述三个位置的信息,被广播描述9个信息

array([[1, 2, 1],
       [3, 4, 3],
       [5, 6, 5]])

In [196]:
arr32

array([[1, 0, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [198]:
arr32[np.ix_([0,1,2],[0,1,0])]  

array([[1, 0, 1],
       [4, 5, 4],
       [7, 8, 7]])

也可以利用数字索引生成同样维度的数组：即切片后的数组与原数组维度一致

In [98]:
arr34 = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
arr34

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
#切取四个角的元素
arr34[[0,0,3,3],[0,2,0,2]]

array([ 0,  2,  9, 11])

In [109]:
# 作为了解
#保持原数组结构的情况下切取四个角的元素
arr34[[[0,0],[3,3]],[[0,2],[0,2]]]  #[[0,0],[3,3]]是切取的四个数字的行坐标位置,[[0,2],[0,2]]是切取的四个数字的列坐标位置
# 也可以写成这种形式,方便查看
# arr34[[[0,0],[3,3]],
#   [[0,2],[0,2]]]

array([[ 0,  2],
       [ 9, 11]])

In [101]:
# 或者这种形式也可以,表示切取的是[0,0],[0,2],[3,0],[3,2]四个元素
rows=[[0,0],[3,3]]
cols=[[0,2],[0,2]]
arr34[rows,cols]

array([[ 0,  2],
       [ 9, 11]])

In [111]:
arr34[[0,-1]][:,[0,-1]] #先切出行信息,在此基础上切列信息,原理和前边切取单个元素的原理一样

array([[ 0,  2],
       [ 9, 11]])

In [102]:
#小练习,切取4,5,7,8四个元素并保持和原数组维度一致
rows1=[[1,1],[2,2]]
cols1=[[1,2],[1,2]]
arr34[rows1,cols1]

array([[4, 5],
       [7, 8]])

In [103]:
#不要忘了前边学过的基本索引和切片
arr34[1:3,1:]

array([[4, 5],
       [7, 8]])

##### 布尔索引

In [112]:
#一维数组的布尔索引
arr1

array([ 1.  ,  3.14, -5.  ,  2.  ,  6.2 ,  0.  ])

In [113]:
arr1>3

array([False,  True, False, False,  True, False])

In [114]:
arr1[arr1>3]

array([3.14, 6.2 ])

In [115]:
#高维数组的布尔索引
arr34

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
arr34<6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [117]:
arr34[arr34<6]

array([0, 1, 2, 3, 4, 5])

In [118]:
arr33

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
#切取符合条件的行信息
rowsum = arr33.sum(-1)  #返回指定轴上元素的和,-1表示最后一个轴,最里边那一个维度的元素求和,每个列的元素相加
rowsum

array([ 3,  7, 11])

In [120]:
rowsum>5

array([False,  True,  True])

In [121]:
arr33[rowsum>5]  #行元素相加大于的5的行切取出来

array([[3, 4],
       [5, 6]])

In [250]:
#切取符合条件的列信息
colsum = arr33.sum(0)  #返回指定轴上元素的和,0表示第一个轴,最外边那一个维度的元素求和,每个行的信息相加

In [251]:
colsum>9

array([False,  True])

In [253]:
arr33[:,colsum>9]

array([[2],
       [4],
       [6]])

In [255]:
#通过"取非"切取非空值元素
arr35 = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
arr35 

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [256]:
arr35[~np.isnan(arr35)]

array([1., 2., 3.])

### numpy--运算

涉及的函数列表

|算术运算|三角函数|复数数组|取整函数|统计函数|唯一化和集合逻辑|排序和索引函数|字符串函数|
|--------|--------|--------|--------|--------|----------------|----------|--------------|
|add(x1，x2 )|sin(x)|numpy.real()|numpy.around()|numpy.amin()|numpy.unique()|numpy.sort()|numpy.char.add()|
|subtract(x1，x2)|cos(x)|numpy.imag()|numpy.floor()|numpy.amax()|numpy.in1d()|numpy.argsort()|numpy.char.multiply()|
|multiply(x1，x2)|tan(x)|numpy.conj()|numpy.ceil()|numpy.ptp()|numpy.intersect1d()|numpy.lexsort()|numpy.char.center()|
|divide(x1，x2)|arcsin(x)|numpy.angle()|-|numpy.percentile()|numpy.union1d()|numpy.argmax()|numpy.char.capitalize()|
|exp(x)|arccos(x)|-|-|numpy.median()|numpy.setdiff1d()|numpy.argmin()|numpy.char.title()|
|exp2(x)|arctan(x)|-|-|numpy.mean()|-|numpy.nonzero()|numpy.char.lower()|
|power(x1,x2)|-|-|-|numpy.average()|-|numpy.where()|numpy.char.upper()|
|mod(x)|-|-|-|numpy.std()|-|numpy.extract()|numpy.char.split()| 
|log(x)|-|-|-|numpy.var()|-|-|numpy.char.splitlines()|
|log2(x)|-|-|-|-|-|-|umpy.char.strip()|
|log10(x)|-|-|-|-|-|-|numpy.char.join()|
|sqrt(x)|-|-|-|-|-|-|numpy.char.replace()|
|square(x)|-|-|-|-|-|-|-|

#### 算术运算相关函数 
（如 add() ，subtract() ，multiply() 和 divide() ）输入的数组必须具有相同的形状或符合数组广播规则。

|**数学运算函数**||
| -------------------------- | ------------------------|
| add(x1，x2 )| 按元素添加参数，等效于 x1 + x2|
| subtract(x1，x2)| 按元素方式减去参数，等效于x1 - x2|
| multiply(x1，x2)| 逐元素乘法参数，等效于x1 * x2|
| divide(x1，x2)| 逐元素除以参数，等效于x1 / x2|
| exp(x)| 计算e的x次方|
| exp2(x)| 计算2的x次方|
| power(x1,x2)| 计算x1的x2次幂|
| mod(x)| 返回输入数组中相应元素的除法余数|
| log(x)| 自然对数，逐元素|
| log2(x)| 以2为底x对数|
| log10(x)| 以10为底x的对数|
| sqrt(x)| 按元素方式返回数组的正平方根|
| square(x)| 返回输入的元素平方|

In [124]:
arr34

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
arr36=np.array([2,2,2])
arr36

array([2, 2, 2])

In [268]:
# 执行数组的加法
np.add(arr34, arr36)
arr34+arr36

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [269]:
#执行数组的减法
np.subtract(arr34, arr36)
arr34-arr36

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [270]:
#执行数组的位乘法
np.multiply(arr34,arr36)
arr34*arr36

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [271]:
#执行数组的位除法
np.divide(arr34,arr36)
arr34/arr36

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [123]:
arr36

array([2, 2, 2])

In [272]:
#执行指数函数
np.exp(arr36)  #自然常数e的幂运算
np.exp2(arr36) #2的幂运算

array([7.3890561, 7.3890561, 7.3890561])

array([4., 4., 4.])

In [273]:
#执行幂函数
np.power(3,arr36)
np.power(arr36,3)

array([9, 9, 9], dtype=int32)

array([8, 8, 8], dtype=int32)

In [125]:
arr34

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [274]:
# 返回输入数组中相应元素的除法余数
np.mod(arr34,arr36)  #arr34/arr36中对应元素的余数

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

#### 复数数组函数(选讲)
- numpy.real():返回复数类型参数的实部
- numpy.imag():返回复数类型参数的虚部
- numpy.conj():返回通过改变虚部的符号而获得的共轭复数

In [4]:
#新建一个复数数组
arr35 = np.array([-5.6j, 0.2j, 11. , 1+1j])
arr35

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+1.j ])

In [6]:
#返回实部
np.real(arr35)

array([-0.,  0., 11.,  1.])

In [7]:
#返回虚部
np.imag(arr35)

array([-5.6,  0.2,  0. ,  1. ])

In [9]:
#共轭复数数组  两个实部相等，虚部互为相反数的复数互为共轭复数
np.conj(arr35)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

 #### 取整函数
- numpy.around()
这个函数返回四舍五入到所需精度的值。
- numpy.floor() 向下取整
此函数返回不大于输入参数的最大整数。
- numpy.ceil()向上取整   本函数返回输入值的上限

In [174]:
arr36 = np.array([1.5,5.55, 123, 0.567, 25.532])
arr36

array([  1.5  ,   5.55 , 123.   ,   0.567,  25.532])

In [130]:
np.around(arr36)
np.around(arr36, decimals = 1,)
np.around(arr36, decimals = -1)
#decimals 表示要舍入的小数位数。默认值为 0。如果为负，整数将四舍五入到小数点左侧的位置(个位数被四舍五入掉)

array([  2.,   6., 123.,   1.,  26.])

array([  1.5,   5.6, 123. ,   0.6,  25.5])

array([  0.,  10., 120.,   0.,  30.])

In [131]:
np.around([.5, 1.5, 2.5, 3.5, 4.5])
# 对于正好在舍入小数值之间的值，NumPy舍入到最接近的偶数值

array([0., 2., 2., 4., 4.])

In [132]:
arr36

array([  1.5  ,   5.55 , 123.   ,   0.567,  25.532])

In [133]:
np.ceil(arr36)
# 标量 x 的上限是最小的整数 i ，使得 i> = x。

array([  2.,   6., 123.,   1.,  26.])

In [175]:
np.floor(arr36) #向下取整

array([  1.,   5., 123.,   0.,  25.])

#### 统计函数
NumPy有很多有用的统计函数，用于从数组中给定的元素中查找最小，最大，百分标准差和方差等。    

|**常用统计函数** ||
| ----------- | ------------------------------- |
|numpy.amin() |从给定数组中的元素沿指定轴返回最小值|
|numpy.amax() |从给定数组中的元素沿指定轴返回最大值|
|numpy.ptp()  |返回沿轴的值的极差（最大值 - 最小值）|
|numpy.percentile()|返回特定轴的百分位数|
|numpy.median()|返回数组中值|
|numpy.mean()|返回数组的算术平均值|
|numpy.average()|返回数组的加权平均值|
|numpy.std()|返回数组的标准差|
|numpy.var()|返回数组的方差|

In [115]:
# numpy.amin() 和 numpy.amax()从给定数组中的元素沿指定轴返回最小值和最大值。
arr37 = np.array([[3,7,5],[8,4,3],[2,4,9]])
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [137]:
np.amin(arr37)
np.amin(arr37,axis=0)  #每一列的最小值,第一个轴
np.amin(arr37,axis=1)  #每一行的最小值,第二个轴

2

array([2, 4, 3])

array([3, 3, 2])

In [138]:
np.amax(arr37)
np.amax(arr37,axis=0)
np.amax(arr37,axis=1)

9

array([8, 7, 9])

array([7, 8, 9])

In [139]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [140]:
# 本函数返回沿轴的值的极差（最大值 - 最小值）
np.ptp(arr37)
np.ptp(arr37,axis=0) #第一个轴,列信息
np.ptp(arr37,axis=1) #第二个轴,行信息

7

array([6, 3, 6])

array([4, 5, 7])

In [105]:
arr38=np.random.randint(0,20,(3,3))
arr38

array([[ 4, 12,  8],
       [16, 12, 12],
       [ 0,  0,  8]])

In [106]:
# 百分位数是统计中使用的度量，表示有指定百分比个数的元素小于返回的数值
np.percentile(arr38, 50)  #a 输入数组  q 要计算的百分位数，在 0 ~ 100 之间   axis 沿着它计算百分位数的轴
np.percentile(arr38, 50,axis = 0)
np.percentile(arr38, 50,axis = 1)  

8.0

array([ 4., 12.,  8.])

array([ 8., 12.,  0.])

In [107]:
# 中值定义为将数据样本的上半部分与下半部分分开的值。
np.median(arr38)
np.median(arr38, axis = 0)
np.median(arr38, axis = 1)

8.0

array([ 4., 12.,  8.])

array([ 8., 12.,  0.])

In [113]:
# arr38.flatten()

In [70]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [69]:
# 算术平均值是沿轴的元素的总和除以元素的数量。函数返回数组中元素的算术平均值。如果提供了轴，则沿其计算。
np.mean(arr37)
np.mean(arr37, axis = 0)
np.mean(arr37, axis = 1)

5.0

array([4.33333333, 5.        , 5.66666667])

array([5., 5., 5.])

In [76]:
arr37.sum()

45

In [74]:
arr37.size

9

In [78]:
arr37[:,0].sum()

13

In [80]:
arr37[:,1].sum()

15

In [81]:
arr37[:,1].size

3

In [103]:
# 加权平均值是由每个分量乘以反映其重要性的因子(即权重)得到的平均值。函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。
# 该函数可以接受一个轴参数。如果没有指定轴，则数组会被展开。
arr39=np.array([1,2,3,4])
arr39

array([1, 2, 3, 4])

In [104]:
np.average(arr39) #不指定权重的时候,函数功能和np.mean()一样

2.5

In [105]:
np.mean(arr39)

2.5

In [106]:
wst = np.array([4,3,2,1])
wst

array([4, 3, 2, 1])

In [107]:
np.average(arr39,weights=wst)

2.0

In [108]:
1*4/wst.sum()+2*3/wst.sum()+3*2/wst.sum()+4*1/wst.sum()

2.0

In [110]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [100]:
wgt=np.array([[9,8,7],[6,5,4],[3,2,1]])
wgt

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [95]:
np.average(arr37,weights = wgt)

4.911111111111111

In [93]:
wgt.sum()

45

In [96]:
3*9/45+7*8/45+5*7/45+8*6/45+4*5/45+3*4/45+2*3/45+4*2/45+9*1/45

4.911111111111112

In [109]:
np.average(arr37,axis=0)

array([4.33333333, 5.        , 5.66666667])

In [111]:
np.average(arr37,axis=1)

array([5., 5., 5.])

In [112]:
wei=np.array([5,3,2])
wei

array([5, 3, 2])

In [115]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [114]:
np.average(arr37,weights=wei,axis=0)

array([4.3, 5.5, 5.2])

In [116]:
3*0.5+8*0.3+2*0.2

4.3

In [117]:
np.average(arr37,weights=wei,axis=1)

array([4.6, 5.8, 4. ])

In [118]:
3*0.5+7*0.3+5*0.2

4.6

In [116]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [119]:
np.average(arr37,weights=wei,axis=1,returned=True) #returned=True返回权重和

(array([4.6, 5.8, 4. ]), array([10., 10., 10.]))

In [121]:
# 标准差是与均值的偏差的平方的平均值的平方根。标准差公式如下： std = sqrt(mean((x - x.mean())**2))
np.std([1,2,3,4])

1.118033988749895

In [122]:
np.std([10,20,30,40])

11.180339887498949

In [123]:
# 方差是偏差的平方的平均值，即mean((x - x.mean())** 2)。换句话说，标准差是方差的平方根。
np.var([1,2,3,4])

1.25

In [124]:
np.var([10,20,30,40])

125.0

#### 唯一化和集合逻辑
- np.unique()  去重函数
- np.in1d()  验证元素是否在给定序列中
- np.intersect1d()  求交集
- np.union1d()  求并集
- np.setdiff1d() 求差集

In [117]:
#字符串去重
names = np.array(['Atom', 'Lucy', 'Kid', 'Atom', 'Kid', 'Atom'])
names
np.unique(names)

array(['Atom', 'Lucy', 'Kid', 'Atom', 'Kid', 'Atom'], dtype='<U4')

array(['Atom', 'Kid', 'Lucy'], dtype='<U4')

In [118]:
set(names)

{'Atom', 'Kid', 'Lucy'}

In [127]:
#整数去重
arr37
np.unique(arr37)

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

array([2, 3, 4, 5, 7, 8, 9])

In [132]:
#布尔值去重
arr40=arr37>5
arr40
np.unique(arr40)

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

array([False,  True])

In [133]:
#布尔值的any()和all()函数
arr40.any() #有一个True就返回True
arr40.all() #所有都为True才返回True

True

False

In [148]:
np.random.seed(1)
arr41=np.random.randint(1,20,(5,))
arr41

array([ 6, 12, 13,  9, 10])

In [149]:
# 验证 指定数组(arr41)中的元素是否在给出的序列(arr42)中
np.random.seed(2)
arr42=np.random.randint(1,20,(5,))
arr42
np.in1d(arr41,arr42)

array([ 9, 16, 14,  9, 12])

array([False,  True, False,  True, False])

In [151]:
np.in1d(arr41,arr42,invert=True) #反转参数

array([ True, False,  True, False,  True])

In [152]:
#求交集
np.intersect1d(arr41,arr42)

array([ 9, 12])

In [154]:
np.intersect1d(arr41,arr42,return_indices=True) 
#参数return_indices=True在返回值的同时返回值所对应的索引

(array([ 9, 12]), array([3, 1], dtype=int64), array([0, 4], dtype=int64))

In [153]:
#求并集  
np.union1d(arr41,arr42)

array([ 6,  9, 10, 12, 13, 14, 16])

In [157]:
arr41
arr42

array([ 6, 12, 13,  9, 10])

array([ 9, 16, 14,  9, 12])

In [156]:
# 求差集,返回前边数组有包含后边数组不包含的元素
np.setdiff1d(arr41,arr42)  
np.setdiff1d(arr42,arr41)

array([ 6, 10, 13])

array([14, 16])

#### 排序和索引函数
|函数名|函数作用|
|------|--------|
|numpy.sort()|返回输入数组的排序副本。|
|numpy.argsort()|对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。这个索引数组用于构造排序后的数组。|
|numpy.lexsort()|使用键序列执行间接排序。键可以看作是电子表格中的一列。返回一个索引数组，使用它可以获得排序数据。注意,最后一个键恰好是 sort 的主键。|
|numpy.argmax()|沿给定轴返回最大元素的索引|
| numpy.argmin()|沿给定轴返回最小元素的索引
|numpy.nonzero()| 返回输入数组中非零元素的索引。|
|numpy.where()|返回输入数组中满足给定条件的元素的索引|
|numpy.extract()|返回满足任何条件的元素。|

In [158]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [159]:
np.sort(arr37)  #默认按照最内部的轴排序

array([[3, 5, 7],
       [3, 4, 8],
       [2, 4, 9]])

In [160]:
np.sort(arr37,axis=0) #按最外部的轴进行排序

array([[2, 4, 3],
       [3, 4, 5],
       [8, 7, 9]])

In [119]:
# 函数对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。这个索引 数组用于构造排序后的数组。
np.random.seed(0)
arr44=np.random.randint(1,9,(5,))
arr44

array([5, 8, 6, 1, 4])

In [186]:
np.argsort(arr44)

array([3, 4, 0, 2, 1], dtype=int64)

In [187]:
arr44[np.argsort(arr44)]

array([1, 4, 5, 6, 8])

In [188]:
np.sort(arr44)

array([1, 4, 5, 6, 8])

In [121]:
# 函数使用键序列执行间接排序。按照第一列进行排序,有相同元素出现时参考第二列。该函数返回一个索引数组，使用它可以获得排序数据。
arr45 = np.array([1,5,1,4,3,4,4])# First column
arr46 = np.array([9,4,0,4,0,2,1]) # Second column
ind = np.lexsort((arr45,arr46)) # Sort by arr46, then by arr45
ind  #返回的是元素的索引位置

array([2, 4, 6, 5, 3, 1, 0], dtype=int64)

In [122]:
[(arr46[i],arr45[i]) for i in ind]

[(0, 1), (0, 3), (1, 4), (2, 4), (4, 4), (4, 5), (9, 1)]

In [123]:
# numpy.argmax() 和 numpy.argmin()这两个函数分别沿给定轴返回最大和最小元素的索引
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [124]:
np.argmax(arr37)  #返回的结果是索引

8

In [125]:
arr37.flatten()

array([3, 7, 5, 8, 4, 3, 2, 4, 9])

In [214]:
arr37.flatten()[8]

9

In [217]:
#返回最大值索引
np.argmax(arr37, axis = 0)
np.argmax(arr37, axis = 1)

array([1, 0, 2], dtype=int64)

array([1, 0, 2], dtype=int64)

In [218]:
# 返回最小值索引
np.argmin(arr37, axis = 0)
np.argmin(arr37, axis = 1)

array([2, 1, 1], dtype=int64)

array([0, 2, 0], dtype=int64)

In [219]:
arr46

array([9, 4, 0, 4, 0, 2, 1])

In [220]:
# 返回输入数组中非零元素的索引
np.nonzero(arr46)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [222]:
arr46[np.nonzero(arr46)]

array([9, 4, 4, 2, 1])

In [227]:
# 函数返回输入数组中满足给定条件的元素的索引。
np.where(arr46>3)

(array([0, 1, 3], dtype=int64),)

In [228]:
np.where(arr46>3,1,-1) #参数设置,满足条件返回1,不满足条件返回-1

array([ 1,  1, -1,  1, -1, -1, -1])

In [224]:
arr38

array([[ 5, 17, 12],
       [ 6,  9,  4],
       [ 7,  3, 11]])

In [225]:
np.where(arr38>6)  #二维数组返回行索引和列索引

(array([0, 0, 1, 2, 2], dtype=int64), array([1, 2, 1, 0, 2], dtype=int64))

In [226]:
arr38[np.where(arr38>6)] #符合条件的元素切片出来

array([17, 12,  9,  7, 11])

In [230]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [231]:
np.where(arr37>arr38,arr37,arr38) #两个数组做比较,返回数值较大的那一个

array([[ 5, 17, 12],
       [ 8,  9,  4],
       [ 7,  4, 11]])

In [ ]:
# 函数返回满足任何条件的元素

In [126]:
condition = np.mod(arr37,2) == 0  #np.mod()求两个数的余数
condition

array([[False, False, False],
       [ True,  True, False],
       [ True,  True, False]])

In [235]:
np.extract(condition, arr37)

array([8, 4, 2, 4])

In [236]:
con=arr37%2==0
con

array([[False, False, False],
       [ True,  True, False],
       [ True,  True, False]])

#### 字符串函数
以下函数用于对 dtype 为 numpy.string_ 或 numpy.unicode_ 的数组执行向量化字符串操作。

|函数名|函数作用|
|------|--------|
|numpy.char.add()|函数执行按元素的字符串连接|
|numpy.char.multiply()|这个函数执行多重连接|
|numpy.char.center()|此函数返回所需宽度的数组，以便输入字符串位于中心，并使用 fillchar 在左侧和右侧进行填充|
|numpy.char.capitalize()|函数返回字符串的副本，其中第一个字母大写|
|numpy.char.title()|返回输入字符串的按元素标题转换版本，其中每个单词的首字母都大写|
|numpy.char.lower()|函数返回一个数组，其元素转换为小写。它对每个元素调用 str.lower|
|numpy.char.upper()|函数返回一个数组，其元素转换为大写。它对每个元素调用 str.upper|
|numpy.char.split()|此函数返回输入字符串中的单词列表。默认情况下，空格用作分隔符。否则，指定的分隔符字符用于分割字符串|
|numpy.char.splitlines()|函数返回数组中元素的单词列表，以换行符分割：'\n'，'\r'，'\r\n' 都被当做换行符处理|
|numpy.char.strip()|函数返回数组的副本，其中元素移除了开头或结尾处的特定字符|
|numpy.char.join()|这个函数返回一个字符串，其中单个字符由特定的分隔符连接|
|numpy.char.replace()|这个函数返回字符串副本，其中所有字符序列的出现位置都被另一个给定的字符序列取代|

In [1]:
# numpy.char.add()函数执行按元素的字符串连接
str1 = np.array([["Hello"],["Hi"]])
str1

array([['Hello'],
       ['Hi']], dtype='<U5')

In [2]:
str2 = np.array([["abc"],["xyz"]])
str2

array([['abc'],
       ['xyz']], dtype='<U3')

In [3]:
np.char.add(str1,str2)

array([['Helloabc'],
       ['Hixyz']], dtype='<U8')

In [127]:
str3=np.array([["cc"],["dd"],["ee"]]) #如果是两个array拼接,形状必须相同
str3

array([['cc'],
       ['dd'],
       ['ee']], dtype='<U2')

In [9]:
np.char.add(str1,str3)

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [10]:
np.char.add(str1, "是嘛?")

array([['Hello是嘛?'],
       ['Hi是嘛?']], dtype='<U8')

In [128]:
# numpy.char.multiply()这个函数执行多重连接
np.char.multiply('Hello ',3)  #乘

array('Hello Hello Hello ', dtype='<U18')

In [12]:
np.char.multiply(str1, 3)

array([['HelloHelloHello'],
       ['HiHiHi']], dtype='<U15')

In [15]:
# numpy.char.center()此函数返回所需宽度的数组，以便输入字符串位于中心，并使用 fillchar 在左侧和右侧进行填充
np.char.center('hello', 11,fillchar = '*')

array('***hello***', dtype='<U11')

In [129]:
'{:*^11}'.format("hello")  #字符串格式化

'***hello***'

In [17]:
np.char.center(str1, 10,fillchar = '*')

array([['**Hello***'],
       ['****Hi****']], dtype='<U10')

In [18]:
# numpy.char.capitalize()函数返回字符串的副本，其中第一个字母大写
np.char.capitalize('hello world')

array('Hello world', dtype='<U11')

In [130]:
str4 = np.array(['hello world', "how are you?"])
str4

array(['hello world', 'how are you?'], dtype='<U12')

In [20]:
np.char.capitalize(str4)

array(['Hello world', 'How are you?'], dtype='<U12')

In [21]:
# numpy.char.title(),返回输入字符串的按元素标题转换版本，其中每个单词的首字母都大写
np.char.title('hello how are you?')

array('Hello How Are You?', dtype='<U18')

In [22]:
np.char.title(str4)

array(['Hello World', 'How Are You?'], dtype='<U12')

In [23]:
# numpy.char.lower()函数返回一个数组，其元素转换为小写。它对每个元素调用 str.lower
str5 = np.array(['HELLO','WORLD'])
np.char.lower(str5)

array(['hello', 'world'], dtype='<U5')

In [24]:
np.char.lower("Hello")

array('hello', dtype='<U5')

In [25]:
# numpy.char.upper()函数返回一个数组，其元素转换为大写。它对每个元素调用 str.upper
np.char.upper('world')

array('WORLD', dtype='<U5')

In [26]:
np.char.upper(str4)

array(['HELLO WORLD', 'HOW ARE YOU?'], dtype='<U12')

In [132]:
str4

array(['hello world', 'how are you?'], dtype='<U12')

In [131]:
# numpy.char.split()此函数返回输入字符串中的单词列表。默认情况下，空格用作分隔符。否则，指定的分隔符字符用于分割字符串.
# 每一对引号分割为一个列表
np.char.split(str4)

array([list(['hello', 'world']), list(['how', 'are', 'you?'])],
      dtype=object)

In [133]:
np.char.split(str4,sep = ',')

array([list(['hello world']), list(['how are you?'])], dtype=object)

In [134]:
np.char.split ('TutorialsPoint,Hyderabad,Telangana', sep = ',')  #以逗号为分割标记

array(list(['TutorialsPoint', 'Hyderabad', 'Telangana']), dtype=object)

In [29]:
np.char.split ('TutorialsPoint,Hyderabad,Telangana', sep = 'a')

array(list(['Tutori', 'lsPoint,Hyder', 'b', 'd,Tel', 'ng', 'n', '']),
      dtype=object)

In [31]:
np.char.split ('TutorialsPoint,Hyderabad,Telangana', sep = 'a',maxsplit=4) #最多分成0-n分

array(list(['Tutori', 'lsPoint,Hyder', 'b', 'd,Tel', 'ngana']),
      dtype=object)

In [32]:
# numpy.char.splitlines()函数返回元素中的行列表，以换行符分割：'\n'，'\r'，'\r\n' 都被当做换行符处理
np.char.splitlines('hello\nhow are you?')

array(list(['hello', 'how are you?']), dtype=object)

In [33]:
np.char.splitlines('hello\nhow are you?',keepends=True) #keepends=True保留换行符在切分后的列表中,默认不保留

array(list(['hello\n', 'how are you?']), dtype=object)

In [34]:
np.char.splitlines('hello\nhow are you?',keepends=False)

array(list(['hello', 'how are you?']), dtype=object)

In [35]:
np.char.splitlines('hello\rhow are you?')

array(list(['hello', 'how are you?']), dtype=object)

In [37]:
str4

array(['hello world', 'how are you?'], dtype='<U12')

In [135]:
np.char.split(str4)

array([list(['hello', 'world']), list(['how', 'are', 'you?'])],
      dtype=object)

In [39]:
np.char.splitlines(str4)  #和split结果一样,都是以一对引号为分割,分成两个列表

array([list(['hello world']), list(['how are you?'])], dtype=object)

In [40]:
# numpy.char.strip()函数返回数组的副本，其中元素移除了开头或结尾处的特定字符,没对引号为一个删除单位
np.char.strip('ashok arora','a')  #默认删除空格

array('shok aror', dtype='<U11')

In [41]:
np.char.strip(['arora','admin','java'],'a')

array(['ror', 'dmin', 'jav'], dtype='<U5')

In [43]:
np.char.strip(str4,'h')

array(['ello world', 'ow are you?'], dtype='<U12')

In [45]:
# numpy.char.replace()这个函数返回字符串副本，其中所有字符序列的出现位置都被另一个给定的字符序列取代
np.char.replace('she is a bad girl', 'is', 'was')

array('she was a bad girl', dtype='<U18')

In [177]:
str5 = np.array([["she is a good student"],["she is a bad girl"]])
str5

array([['she is a good student'],
       ['she is a bad girl']], dtype='<U21')

In [47]:
np.char.replace(str5, 'is', 'was')

array([['she was a good student'],
       ['she was a bad girl']], dtype='<U22')

In [49]:
str5

array([['she is a good student'],
       ['she is a bad girl']], dtype='<U21')

In [180]:
np.char.replace(str5, 'is', 'was',count=1)  #次数限制一维数组内替换次数

array([['she was a good student'],
       ['she was a bad girl']], dtype='<U22')

In [52]:
str6 = np.array(["Lucy is a good student and Lily is a bad girl"])
str6

array(['Lucy is a good student and Lily is a bad girl'], dtype='<U45')

In [54]:
np.char.replace(str6, 'is', 'was',count=1)

array(['Lucy was a good student and Lily is a bad girl'], dtype='<U46')

###  NumPy - 矩阵库
NumPy 包包含一个 Matrix 库 numpy.matlib 。此模块的函数返回矩阵而不是返回 ndarray对象。

|函数名|函数作用|
|------|--------|
|matlib.empty()|函数返回一个新的矩阵，且不初始化元素|
|numpy.matlib.zeros()|此函数返回以0填充的矩阵|
|numpy.matlib.ones()|此函数返回以1填充的矩阵|
|numpy.matlib.eye()|这个函数返回一个矩阵，对角线元素为 1，其他位置为零|
|numpy.matlib.identity()|函数返回给定大小的单位矩阵。单位矩阵是主对角线元素都为 1 的方阵|
|numpy.matlib.rand()|函数返回给定大小的填充随机值的矩阵|

In [181]:
import numpy.matlib

In [137]:
# matlib.empty()函数返回一个新的矩阵，且不初始化元素。
mat1 = np.matlib.empty((2,2))
mat1

matrix([[0.00000000e+000, 6.95215129e-310],
        [9.88131292e-324,             nan]])

In [138]:
type(mat1)

numpy.matrixlib.defmatrix.matrix

In [139]:
mat1.fill(2)

In [140]:
mat1

matrix([[2., 2.],
        [2., 2.]])

In [59]:
# numpy.matlib.zeros()此函数返回以0填充的矩阵。
np.matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [61]:
# numpy.matlib.ones()此函数返回以1填充的矩阵。
np.matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [63]:
# numpy.matlib.eye()这个函数返回一个矩阵，对角线元素为 1，其他位置为零
np.matlib.eye(n = 3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [64]:
np.matlib.eye(n = 3,M = 4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [65]:
np.matlib.eye(n = 3, M = 4, k = 1)

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [66]:
np.matlib.eye(n = 3, M = 4, k = -1)

matrix([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]])

In [67]:
np.matlib.eye(n = 3, M = 4, k = 0, dtype = int)

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0]])

In [68]:
# numpy.matlib.identity()函数返回给定大小的单位矩阵。单位矩阵是主对角线元素都为 1 的方阵
np.matlib.identity(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [69]:
np.matlib.identity(5, dtype = int)

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [70]:
# numpy.matlib.rand()函数返回给定大小的填充随机值的矩阵
np.matlib.rand(3,3)

matrix([[0.03558276, 0.91878865, 0.20108707],
        [0.2708741 , 0.28688433, 0.82094994],
        [0.84883334, 0.3403726 , 0.59750606]])

In [73]:
np.matlib.rand(3,4)

matrix([[0.37184329, 0.5658751 , 0.54387544, 0.93663983],
        [0.07165968, 0.51606178, 0.53499654, 0.49249104],
        [0.1615841 , 0.34881521, 0.94603291, 0.36478251]])

In [74]:
np.matlib.rand(3)

matrix([[0.95693016, 0.15477263, 0.56307442]])

In [75]:
np.matlib.rand((2, 3), 4)  #如果第一个参数是元组,则忽略逗号后边的参数

matrix([[0.02376742, 0.17009779, 0.27035824],
        [0.576     , 0.83574657, 0.96699806]])

注意，矩阵总是二维的，而 ndarray 是一个 n 维数组。两个对象都是可互换的，但是两个对象并不是相同的。

In [141]:
mat1

matrix([[2., 2.],
        [2., 2.]])

In [142]:
arr=np.array(mat1)
arr

array([[2., 2.],
       [2., 2.]])

In [83]:
#符合形状要求的数组才能转化成矩阵
arr2

array([[5, 6, 7, 8, 9],
       [4, 3, 2, 1, 0]])

In [81]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [88]:
arr8

array([[[46,  2, 31, 20, 42],
        [ 4, 55, 30, 31, 15],
        [30, 29,  9, 11,  9],
        [21, 32, 44, 51,  7]],

       [[17, 35, 49, 15, 49],
        [59, 18, 40, 41, 22],
        [57, 55, 47, 34,  7],
        [21, 19, 42, 39, 45]],

       [[23, 22, 34, 45,  1],
        [59, 59, 32, 30, 22],
        [45, 54, 28, 20, 13],
        [45, 24, 47, 43, 16]]])

In [84]:
mat2 = np.matrix(arr2)
mat2

matrix([[5, 6, 7, 8, 9],
        [4, 3, 2, 1, 0]])

In [92]:
arr4.shape

(1, 3, 3)

In [93]:
arr8.shape

(3, 4, 5)

In [86]:
mat3=np.matrix(arr4)
mat3

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
mat4=np.matrix(arr8) #高维数组且每个维度数量都大于一的数组不能转化成矩阵
mat4

ValueError: shape too large to be a matrix.

### NumPy - 线性代数 
NumPy 包包含 numpy.linalg 模块，提供线性代数所需的所有功能。

|函数名|函数作用|
|------|--------|
|numpy.dot()|返回两个数组的点积|
|numpy.vdot()|返回两个向量的点积|
|numpy.inner()|返回一维数组的向量内积|
|numpy.matmul()|返回两个数组的矩阵乘积|
|numpy.linalg.det()|计算输入矩阵的行列式|
|numpy.linalg.solve()|求解矩阵形式的线性方程的解|
|numpy.linalg.inv()|计算矩阵的逆|

In [ ]:
# numpy.dot()此函数返回两个数组的点积。
# 对于二维向量，其等效于矩阵乘法。
# 对于一维数组，它是向量的内积。
# 对于 N 维数组，它是 a 的最后一个轴上的和与 b 的倒数第二个轴的乘积

In [185]:
arr47_1 = np.array([1,2])
arr48_1 = np.array([3,4])
arr47_1
arr48_1

array([1, 2])

array([3, 4])

In [186]:
np.dot(arr47_1,arr48_1)

11

In [187]:
1*3+2*4

11

In [188]:
np.vdot(arr47_1,arr48_1)

11

In [ ]:
# 用来计算的数组都是一维时,dot和vdot计算结果一样
# 用来计算的数组都是二维时,dot和matmul计算结果一样

In [143]:
arr47 = np.array([[1,2],[3,4]])
arr48 = np.array([[11,12],[13,14]])
arr47
arr48

array([[1, 2],
       [3, 4]])

array([[11, 12],
       [13, 14]])

In [144]:
numpy.dot(arr47,arr48) #矩阵的乘法

array([[37, 40],
       [85, 92]])

In [102]:
1*11+2*13
1*12+2*14
3*11+4*13
3*12+4*14

37

40

85

92

In [184]:
# 在较新版本中支持了以 @ 符号来表示矩阵的乘法
arr47@arr48

array([[37, 40],
       [85, 92]])

In [109]:
# numpy.vdot()此函数返回两个向量的点积。如果第一个参数是复数，那么它的共轭复数会用于计算。如果参数是多维数组，它会被展开
np.vdot(arr47,arr48)

130

In [112]:
arr47_1 = arr47.flatten()
arr47_1

array([1, 2, 3, 4])

In [116]:
arr48_1=arr48.flatten().reshape(4,1)
arr48_1

array([[11],
       [12],
       [13],
       [14]])

In [117]:
np.vdot(arr47_1,arr48_1)

130

In [118]:
1*11+2*12+3*13+4*14

130

In [119]:
# numpy.inner()此函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的乘积的和
np.inner(np.array([1,2,3]),
               np.array([0,1,0]))  #等价于1*0+2*1+3*0

2

In [120]:
arr47
arr48

array([[1, 2],
       [3, 4]])

array([[11, 12],
       [13, 14]])

In [121]:
np.inner(arr47,arr48)

array([[35, 41],
       [81, 95]])

In [123]:
#内积计算过程
1*11+2*12
1*13+2*14 
3*11+4*12
3*13+4*14

35

41

81

95

In [ ]:
# numpy.matmul()函数返回两个数组的矩阵乘积。
# 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于 2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。
# 另一方面，如果任一参数是一 维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。

In [154]:
# 对于二维数组，它就是矩阵乘法
arr51 = np.array([[1,0],[0,1]])
arr52 = np.array([[4,1],[2,2]])
arr51
arr52

array([[1, 0],
       [0, 1]])

array([[4, 1],
       [2, 2]])

In [130]:
np.dot(arr51,arr52)

array([[4, 1],
       [2, 2]])

In [131]:
np.matmul(arr51,arr52)

array([[4, 1],
       [2, 2]])

In [147]:
arr51_1 = np.array([[2,3],[1,3]])
arr52_1= np.array([[4,1],[2,2]])
arr51_1
arr52_1

array([[2, 3],
       [1, 3]])

array([[4, 1],
       [2, 2]])

In [148]:
np.matmul(arr51_1,arr52_1)

array([[14,  8],
       [10,  7]])

In [149]:
np.dot(arr51_1,arr52_1)

array([[14,  8],
       [10,  7]])

In [151]:
np.vdot(arr51_1,arr52_1) #把二维数组碾平成一维进行运算

19

In [152]:
2*4+3*1+1*2+3*2

19

In [155]:
# 二维和一维运算
arr51
arr53 = np.array([1,2])
arr53

array([[1, 0],
       [0, 1]])

array([1, 2])

In [157]:
arr51_1

array([[2, 3],
       [1, 3]])

In [156]:
np.matmul(arr51_1,arr53)

array([8, 7])

In [158]:
2*1+3*2
1*1+3*2

8

7

In [159]:
np.matmul(arr51,arr53)

array([1, 2])

In [160]:
1*1+0*2
0*1+1*2

1

2

In [161]:
 # 维度大于二的数组
arr54 = np.arange(8).reshape(2,2,2)
arr55 = np.arange(4).reshape(2,2)
arr54
arr55

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[0, 1],
       [2, 3]])

In [162]:
np.matmul(arr54,arr55)

array([[[ 2,  3],
        [ 6, 11]],

       [[10, 19],
        [14, 27]]])

In [165]:
#分解运算查看
arr_1 = np.array([[0,1],[2,3]])
arr_1

array([[0, 1],
       [2, 3]])

In [166]:
np.matmul(arr_1,arr_1)

array([[ 2,  3],
       [ 6, 11]])

In [168]:
arr_2 = np.array([[4,5],[6,7]])
arr_2

array([[4, 5],
       [6, 7]])

In [170]:
np.matmul(arr_2,arr_1)

array([[10, 19],
       [14, 27]])

In [141]:
# numpy.linalg.det()函数计算输入矩阵的行列式。行列式在线性代数中是非常有用的值
arr47

array([[1, 2],
       [3, 4]])

In [143]:
np.linalg.det(arr47)

-2.0000000000000004

In [144]:
1*4-2*3

-2

In [146]:
arr37

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [147]:
np.linalg.det(arr37)

-269.99999999999983

In [148]:
3*4*9+7*3*2+5*8*4-2*4*5-8*7*9-3*4*3

-270

In [150]:
# numpy.linalg.solve()   函数给出了矩阵形式的线性方程的解。

 例如，考虑以下线性方程：   
`x + y + z = 6`   
`2y + 5z = -4`    
`2x + 5y - z = 27`    

可以使用矩阵表示为：

$
\left[
 \begin{matrix}
   1 & 1 & 1 \\
   0 & 2 & 5 \\
   2 & 5 & -1
  \end{matrix}
  \right]
  $
.
$
\left[
 \begin{matrix}
   x \\
   y \\
   z 
  \end{matrix}
  \right]
$
=
$
\left[
 \begin{matrix}
   6 \\
  -4 \\
   27 
  \end{matrix}
  \right]
  $
  
 如果矩阵成为 A 、X 和 B ，方程变为：AX = B

In [151]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
B = np.array([6,-4,27])
A
B

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

array([ 6, -4, 27])

In [152]:
X = np.linalg.solve(A, B)
X

array([ 5.,  3., -2.])

In [153]:
np.allclose(np.dot(A,X),B) #判断两者是否相等

True

In [157]:
# numpy.linalg.inv()函数来计算矩阵的逆
arr47

array([[1, 2],
       [3, 4]])

In [159]:
arr56=np.linalg.inv(arr47)
arr56

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##  NumPy - IO 

ndarray 对象可以保存到磁盘文件并从磁盘文件加载。可用的 IO 功能有：
- load() 和 save() 函数处理 NumPy 二进制文件（带 npy 扩展名）
- loadtxt() 和 savetxt() 函数处理正常的文本文件

NumPy 为 ndarray 对象引入了一个简单的文件格式。这个 npy 文件在磁盘文件中，存储重建ndarray 所需的数据、图形、dtype 和其他信息，以便正确获取数组，即使该文件在具有不同架构的另一台机器上。

In [166]:
# numpy.save()文件将输入数组存储在具有 npy 扩展名的磁盘文件中。
arr56
np.save('outfile',arr56)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [168]:
# 为了从 outfile.npy 重建数组，请使用 load() 函数。
arr57=np.load('outfile.npy')
arr57

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [170]:
# savetxt()以简单文本文件格式存储和获取数组数据，是通过 savetxt() 和 loadtxt() 函数完成的
arr47
np.savetxt('out.txt',arr47)

array([[1, 2],
       [3, 4]])

In [173]:
arr58=np.loadtxt('out.txt')  
#delimiter=None原文件的分隔符是什么  skiprows=0 设置跳过第几行,设置等于1时用于跳过表头  usecols=None使用原数据集中的哪几列  
arr58

array([[1., 2.],
       [3., 4.]])

In [3]:
arr = np.random.randint(10,50,(2,3))
arr

array([[12, 47, 27],
       [31, 11, 40]])