**NumPy**是Python语言的一个扩充程序库。支持大量高维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。机器学习涉及到大量对数组的变换和运算，NumPy就成了必不可少的工具之一。
**NumPy百题大冲关**分为基础篇和进阶篇，每部分各有50道练习题。基础部分的练习题在于熟悉NumPy常用方法的使用，而进阶部分则侧重于NumPy方法的组合应用。

**实验知识点**
- 创建数组
- 数组运算
- 数学函数
- 数组切片和索引
- 数组形状操作
- 数组排序
- 数组统计

**实验环境**
- Python3.6及以上
- NumPy：1.14.3

## 基础部分

### 导入NumPy

**1、导入NumPy**

练习NumPy之前，首先需要导入NumPy模块，并约定简称为 "np"。

In [1]:
import numpy as np

**2、查看NumPy版本信息**

In [ ]:
np.__version__

### 创建数组

NumPy的主要对象是多维数组Ndarray。在NumPy中维度（dimension）叫做轴（axes），轴的个数叫做秩（rank）。

例如，下方数组是一个秩为1的数组，因为它只有一个轴，而轴的长度为3。

```
[1,2,3]
```

又例如，下方数组的秩为2。第一个维度为2，第二个维度长度为3。

```
[[1,2,3],
 [4,5,6]]
 ```

**3、通过列表创建一维数组**

注意：`numpy.array` 和Python标准库 `array.array` 并不相同，前者更为强大，这也是我们学习NumPy的重要原因之一。

In [ ]:
np.array([1,2,3])

**4、通过列表创建二维数组**

In [ ]:
np.array([(1,2,3),(4,5,6)])

**5、创建全为0的二维数组**

In [ ]:
np.zeros((3,3))

**6、创建全为1的三维数组**

In [ ]:
np.ones((2,3,4))

**7、创建一维等差数组**

In [ ]:
np.arange(5)

**8、创建二维等差数组**

In [ ]:
np.arange(6).reshape(2,3)

**9、创建单位矩阵（二维数组）**

In [ ]:
np.eye(3)

**10、创建等间隔一维数组**

In [ ]:
np.linspace(1,10,num=6)

**11、创建二维随机数组**

In [ ]:
np.random.rand(2,3)

**12、创建二维随机整数数组（数值小于5）**

In [ ]:
np.random.randint(5,size=(2,3))

**13、依据自定义函数创建数组**

In [ ]:
np.fromfunction(lambda i , j : i+j,(3,3))

### 数组运算

In [ ]:
# 生成一维示例数组
a = np.array([10,20,30,40,50])
b = np.arange(1,6)

**14、一维数组加法运算**

In [ ]:
a+b

**15、一维数组减法运算**

In [ ]:
a-b

**16、一维数组乘法运算**

In [ ]:
a*b

**17、一维数组除法运算**

In [ ]:
a/b

**18、矩阵加法运算**

In [ ]:
# 生成二维示例数组（可以看作矩阵）
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A,B

In [ ]:
A+B

**19、矩阵减法运算**

In [ ]:
A-B

**20、矩阵元素间乘法运算**

In [ ]:
A*B

**21、矩阵乘法运算（注意与上题的区别）**

In [ ]:
np.dot(A,B)

In [ ]:
np.mat(A)*np.mat(B)

**22、数乘矩阵**

In [ ]:
2*A

**23、矩阵的转置**

In [ ]:
A.T

**24、矩阵求逆**

In [ ]:
np.linalg.inv(A)

In [ ]:
np.dot(A, np.linalg.inv(A))

In [ ]:
np.mat(A)*np.mat(np.linalg.inv(A))

### 数学函数

**25、三角函数**

In [ ]:
np.sin(a)

In [ ]:
np.cos(a)

In [ ]:
np.tan(a)

**26、以自然对数函数为底数的指数函数**

In [ ]:
np.exp(a)

**27、数组的方根的运算（开平方）**

In [ ]:
np.sqrt(a)

**28、数组的方根的运算（开立方）**

In [ ]:
np.power(a,3)

### 数组的索引和切片

**29、一维数组索引**

In [ ]:
a = np.array([1,2,3,4,5])
a[0] , a[1] ,a[2] , a[3] , a[4] 

**30、一维数组切片**

In [ ]:
a[0:2] , a[2:5]

**31、二维数组索引**

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0] , a[1]

**32、二维数组切片（取第2列）**

In [ ]:
a[:,1]

**33、二维数组切片（取第2，3行）**

In [ ]:
a[1:,:]

### 数组形状操作

#### 生成二维示例数组

In [ ]:
a = np.random.random((3,2))
a

**34、查看数组形状**

In [ ]:
a.shape

**35、更改数组形状（不改变原始数组）**

In [ ]:
a.reshape(2,3)

**36、更改数组形状（改变原始数组）**

In [ ]:
a.resize(2,3)
a

**37、展平数组**

In [ ]:
a.flatten()

In [ ]:
a.ravel()

**38、垂直拼合数组**

In [ ]:
a = np.random.randint(10,size=(3,3))
b = np.random.randint(10,size=(3,3))

In [ ]:
np.vstack((a,b))

**39、水平拼合数组**

In [ ]:
np.hstack((a,b))

**40、沿横轴分割数组**

In [ ]:
np.hsplit(a,3)

**41、沿纵轴分割数组**

In [ ]:
np.vsplit(b,3)

### 数组排序

In [ ]:
# 生成示例数组
a = np.array(([1,4,3],[6,2,9],[4,7,2]))
a

**42、返回每列最大值**

In [ ]:
np.max(a,axis=0)

**43、返回每行最小值**

In [ ]:
np.min(a,axis=1)

**44、返回每列最大值索引**

In [ ]:
np.argmax(a,axis=0)

**45、返回每行最小值索引**

In [ ]:
np.argmin(a,axis=1)

### 数组统计

**46、统计数组各列的中位数**

In [ ]:
#继续使用上面的a数组

In [ ]:
np.median(a,axis=0)

**47、统计数组各行的算术平均值**

In [ ]:
np.mean(a,axis=1)

**48、统计数组各列的加权平均值**

In [ ]:
np.average(a,axis=0)

**49、统计数组各行的方差**

In [ ]:
np.var(a,axis=1)

**50、统计数组各列的标准偏差**

In [ ]:
np.std(a,axis=0)

## 进阶部分 

**51、创建一个5×5的二维数组，其中边界值为1，其余值为0**

In [2]:
import numpy as np

In [ ]:
Z = np.ones((5,5))
Z[1:-1,1:-1]=0
Z

In [5]:
Z = np.zeros((5,5))
Z[:1,]=1
Z

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**52、使用数字0将一个全为1的5×5二维数组包围**

In [ ]:
Z = np.ones((5,5))
np.pad(Z,pad_width=1,mode="constant",constant_values=0)

**53、创建一个5×5的二维数组，并设置值1，2，3，4落在其对角线下方**

In [ ]:
np.diag([1,2,3,4],k=-1)

In [ ]:
np.diag(1+np.arange(4),k=-1)

**54、创建一个10×10的二维数组，并使得1和0沿对角线间隔放置**

In [ ]:
Z = np.zeros((10,10),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
Z

**55、创建一个0-10的一维数组，并将(1,9]之间的数全部反转成负数**

In [ ]:
Z = np.arange(11)
Z[(1<Z)&(Z<=9)]*=-1
Z

**56、找出两个一维数组中相同的元素**

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
np.intersect1d(Z1,Z2)

**57、使用NumPy打印昨天、今天、明天的日期**

In [ ]:
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tomorrow)

**58、使用五种不同的方法去提取一个随机数组的整数部分**

In [ ]:
Z = np.random.randint(0,10,10)
print("原始值：",Z)

In [ ]:
# 方法一
Z-Z%1

In [ ]:
# 方法二
np.floor(Z)

In [ ]:
# 方法三
np.ceil(Z)-1

In [ ]:
# 方法四
Z.astype(int)

In [ ]:
# 方法五
np.trunc(Z)

**59、创建一个5×5的矩阵，其中每行的数值范围从1到5**

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(1,6)
Z

In [ ]:
tile

**60、创建一个长度为5的等间隔一维数组，其值域范围从0到1，但是不包括0和1**

In [ ]:
Z = np.linspace(0,1,6,endpoint=False)[1:]
Z

**61、创建一个长度为10的随机一维数组，并将其按升序排序**

In [ ]:
Z = np.random.random(10)
Z.sort()
Z

**62、创建一个3×3的二维数组，并将列按升序排序**

In [ ]:
Z = np.array([[7,4,3],[3,1,2],[4,2,6]])
Z

In [ ]:
Z.sort(axis=0)
Z

**63、创建一个长度为5的一维数组，并将其中最大值替换成0**

In [ ]:
Z = np.random.random(5)
Z[Z.argmax()] = 0
Z

**64、打印每个NumPy标量类型的最小值和最大值**

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print("The minimun value of {}".format(dtype), np.iinfo(dtype).min)
    print("The maximun value of {}".format(dtype),np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print("The minimun value of {}".format(dtype),np.finfo(dtype).min)
    print("The maximum value of {}".format(dtype),np.finfo(dtype).max)

**65、将`float`转换为整型**

In [ ]:
Z = np.arange(10,dtype=np.float32)
print(Z)

In [ ]:
Z = Z.astype(np.int32)
Z

**66、将随机二维数组按照第3列从上到下进行升序排列**

In [ ]:
Z = np.random.randint(0,10,(5,5))
print("排序前：\n",Z)
Z[Z[:,2].argsort()]

**67、从随机数组中找出距离给定数值(0.5)最近的数**

In [ ]:
Z = np.random.uniform(0,1,20)
print("随机数组：\n",Z)
z = 0.5

In [ ]:
m = Z[np.abs(Z-z).argmin()]
m

**68、将二维数组的前两行进行顺序交换**

In [ ]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

**69、找出随机一维数组中出现频率最高的值**

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
np.bincount(Z).argmax()

**70、找出给定一维数组中非0元素的位置索引**

In [ ]:
Z = np.nonzero([1,0,2,0,1,0,4,0])
Z

**71、对于给定的5×5二维数组，在其内部随机放置p个值为1的数**

In [ ]:
p = 3
Z = np.zeros((5,5))
np.put(Z , np.random.choice(range(5*5) , p),1)
Z

**72、对于随机的 3x3 二维数组，减去数组每一行的平均值**

In [ ]:
X = np.random.rand(3,3)
print(X)
Y = X - X.mean(axis=1,keepdims=True)
Y

**73、获得二维数组点积结果的对角线数组**

In [ ]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))
np.dot(A,B)

In [ ]:
#较慢的方法
np.diag(np.dot(A,B))

In [ ]:
#较快的方法
np.sum(A*B.T,axis=1)

**74、找到随机一位数组中前p个最大值**

In [ ]:
Z = np.random.randint(1,100,100)
print(Z)
p = 5
Z[np.argsort(Z)[-p:]]

**75、计算随机一位数组中每个元素的4次方数值**

In [ ]:
X = np.random.randint(2,5,5)
print(X)
np.power(X,4)

**76、对于二维随机数组中各元素，保留其2位小数**

In [ ]:
Z = np.random.random((5,5))
print(Z)
np.set_printoptions(precision=2)
Z

**77、使用科学计数法输出NumPy数组**

In [ ]:
Z  = np.random.random((5,5))
print(Z)
Z/1e3

**78、使用NumPy找出百分位数（25%，50%，75%）**

In [ ]:
a = np.arange(15)
print(a)
np.percentile(a, q = [25,50,76])

**79、找出数组中缺失值的总数及所在位置**

In [ ]:
Z = np.random.rand(10,10)
Z[np.random.randint(10,size=5), np.random.randint(10,size=5)]=np.nan
Z

In [ ]:
print(np.isnan(Z).sum())
print(np.where(np.isnan(Z)))

**80、从随机数组中删除包含缺失值的行**

In [ ]:
# 沿用79
Z[np.sum(np.isnan(Z),axis=1)==0]

**81、统计随机数组中的各元素的数量**

In [ ]:
Z = np.random.randint(0,100,25).reshape(5,5)
print(Z)
np.unique(Z,return_counts=True)

**82、将数组中各元素按指定分类转换为文本值**

In [ ]:
# 指定类别如下
# 1 → 汽车
# 2 → 公交车
# 3 → 火车

In [ ]:
Z = np.random.randint(1,4,10)
print(Z)
label = {1:"汽车",2:"公交车",3:"火车"}
[label[x] for x in Z]

**83、将多个1维数组拼合成单个ndarray**

In [ ]:
Z1 = np.arange(3)
Z2 = np.arange(3,7)
Z3 = np.arange(7,10)
Z = np.array([Z1,Z2,Z3])
print(Z)
np.concatenate(Z)

**84、打印各元素在数组中升序排列的索引**

In [ ]:
a = np.random.randint(100,size  = 10)
print(a)
a.argsort()

**85、得到二维随机数组各行的最大值**

In [ ]:
Z  = np.random.randint(1,100,[5,5])
print(Z)
np.amax(Z,axis=1)

**86、得到二维随机数组各行的最小值（区别上面的方法）**

In [ ]:
Z = np.random.randint(1,100,[5,5])
print(Z)
np.apply_along_axis(np.min,arr=Z,axis=1)

**87、计算两个数组之间的欧氏距离**

In [ ]:
a = np.array([1,2])
b = np.array([7,8])
# 数学计算法
print(np.sqrt(sum(np.power((a-b),2))))
# NumPy计算
np.linalg.norm(b-a)

**88、打印复数的实部和虚部**

In [ ]:
a = np.array([1+2j,3+4j,5+6j])
print(a.real)
print(a.imag)

**89、求解给出矩阵的逆矩阵并验证**

In [ ]:
matrix = np.array([[1,2],[3,4]])
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

In [ ]:
np.allclose(np.dot(matrix,inverse_matrix),np.eye(2))

**90、使用Z-Score标准化算法对数据进行标准化处理**

Z-Score 标准化公式：
$$Z = \frac{X-\mathrm{mean}(X)}{\mathrm{sd}(X)}$$

In [ ]:
#根据公式定义函数
def zscore(x , axis=None):
    xmean = x.mean(axis=axis,keepdims=True)
    xstd = np.std(x, axis=axis, keepdims=True)
    zscore = (x-xmean)/xstd
    return zscore

In [ ]:
# 生成随机数据
Z  = np.random.randint(10,size=(5,5))
print(Z)
zscore(Z)

**91、使用Min-Max标准化算法对数据进行标准化处理**

Min-Max 标准化公式：
$$Y = \frac{Z-\min(Z)}{\max(Z)-\min(Z)}$$

In [ ]:
def min_max(x,axis=None):
    min = x.min(axis=axis,keepdims=True)
    max = x.max(axis=axis,keepdims=True)
    result = (x-min)/(max-min)
    return result

In [ ]:
Z = np.random.randint(10,size=(5,5))
print(Z)
min_max(Z)

**92、使用L2范数对数据进行标准化处理**

L2 范数计算公式：
$$L_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_i^2}$$

In [ ]:
def l2_normalize(v, axis=-1, order=2):
    l2 = np.linalg.norm(v, ord = order, axis=axis, keepdims=True)
    l2[l2==0] = 1
    return v/l2

In [ ]:
Z  = np.random.randint(10,size=(5,5))
print(Z)
l2_normalize(Z)

**93、使用NumPy计算变量直接的相关性系数**

In [ ]:
Z = np.array([[1,2,1,9,10,3,2,6,7],  # 特征A
             [2,1,8,3,7,5,10,7,2],       # 特征B
             [2,1,1,8,9,4,3,5,7]])       # 特征C

np.corrcoef(Z)

相关性系数取值从 `[-1, 1]` 变换，靠近 1 则代表正相关性较强，-1 则代表负相关性较强。结果如下所示，变量 A 与变量 A 直接的相关性系数为 `1`，因为是同一个变量。变量 A 与变量 C 之间的相关性系数为 `0.97`，说明相关性较强。
```
          [A]     [B]     [C]
 array([[ 1.  , -0.06,  0.97]   [A]
        [-0.06,  1.  , -0.01],  [B]
       [ 0.97, -0.01,  1.  ]])  [C]
```

**94、使用NumPy计算矩阵的特征值和特征向量**

In [6]:
M = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
w,v  = np.linalg.eig(M)
w,v

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 matrix([[-0.23197069, -0.78583024,  0.40824829],
         [-0.52532209, -0.08675134, -0.81649658],
         [-0.8186735 ,  0.61232756,  0.40824829]]))

In [7]:
v * np.diag(w) * np.linalg.inv(v)

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

**95、使用NumPy计算ndarray两相邻元素差值**

In [ ]:
Z = np.random.randint(1,10,10)
print(Z)

In [ ]:
# 计算Z两相邻元素差值
np.diff(Z,n=1)
# 重复计算2次
np.diff(Z,n=2)
# 重复计算3次
np.diff(Z,n=3)

**96、使用NumPy将ndarray相邻元素依次累加**

In [ ]:
Z = np.random.randint(1,10,10)
print(Z)

In [ ]:
np.cumsum(Z)

**97、使用NumPy按列连接两个数组**

In [ ]:
M1 = np.array([1,2,3])
M2 = np.array([4,5,6])
np.c_[M1,M2]

**98、使用NumPy按行连接两个数组**

In [ ]:
M1 = np.array([1,2,3])
M2 = np.array([4,5,6])
np.r_[M1,M2]

**99、使用NumPy打印九九乘法表**

In [ ]:
np.fromfunction(lambda i , j : (i +1)* (j+1) , (9,9))